'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {densityColor,orbitPosition} from '@/lib/mission';
import type {Marker} from '@/lib/archive';
type Props={region:any;data:Marker[];visibleOrbits:string[];points:boolean;orbits:boolean;grid:boolean;rotate:boolean;zoom:number;focus:{lat:number;lon:number;key:number}|null;onSelect:(r:Marker)=>void};
export default function Globe(props:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const api=useRef<any>(null);const [error,setError]=useState('');
useEffect(()=>{if(!host.current)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{setError('3D graphics are unavailable. All readings remain accessible in the Data catalog.');return;}const el=host.current;renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor(0,0);el.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(3.7,2.1,4.7).setLength(7.8);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=3;controls.maxDistance=14;controls.autoRotateSpeed=.3;
const geo=(lat:number,lon:number,r=2)=>new THREE.Vector3(r*Math.cos(lat*Math.PI/180)*Math.cos(lon*Math.PI/180),r*Math.sin(lat*Math.PI/180),-r*Math.cos(lat*Math.PI/180)*Math.sin(lon*Math.PI/180));const texture=new THREE.TextureLoader().load('/earth.jpg',()=>{},undefined,()=>setError('Earth imagery could not load. Measurement positions remain available.'));texture.colorSpace=THREE.SRGBColorSpace;const earth=new THREE.Mesh(new THREE.SphereGeometry(2,96,64),new THREE.MeshPhongMaterial({map:texture,color:0x708b9f,shininess:8}));scene.add(earth);scene.add(new THREE.AmbientLight(0xb2d0f0,1.15));const sun=new THREE.DirectionalLight(0xd8eaff,2.2);sun.position.set(4,4,5);scene.add(sun);
scene.add(new THREE.Mesh(new THREE.SphereGeometry(2.065,64,48),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n;varying vec3 v;void main(){float a=pow(1.-abs(dot(n,v)),4.);gl_FragColor=vec4(.12,.48,1.,a*.55);}'})));
const gridGroup=new THREE.Group();for(let lat=-60;lat<=60;lat+=30){const p=[];for(let lon=-180;lon<=180;lon+=2)p.push(geo(lat,lon,2.008));gridGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),new THREE.LineBasicMaterial({color:0x78adc7,transparent:true,opacity:.14})));}for(let lon=-180;lon<180;lon+=30){const p=[];for(let lat=-90;lat<=90;lat+=2)p.push(geo(lat,lon,2.008));gridGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),new THREE.LineBasicMaterial({color:0x78adc7,transparent:true,opacity:.14})));}scene.add(gridGroup);const orbitGroup=new THREE.Group();for(let o=0;o<9;o++){const ps=[];for(let i=0;i<=240;i++){const p=orbitPosition(i/240*Math.PI*2,o);ps.push(geo(p.lat,p.lon,2.19));}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(ps),new THREE.LineBasicMaterial({color:o%3===0?0x68dfff:o%3===1?0x9d8afa:0xf0cb86,transparent:true,opacity:.2}));line.userData.orbit=`ORB-${1420+o}`;orbitGroup.add(line);}scene.add(orbitGroup);
const pointGeo=new THREE.BufferGeometry(),cloud=new THREE.Points(pointGeo,new THREE.PointsMaterial({size:.03,vertexColors:true,transparent:true,opacity:.95,sizeAttenuation:true}));scene.add(cloud);const ray=new THREE.Raycaster();ray.params.Points={threshold:.045};let down={x:0,y:0};const onDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5||!latest.current.points)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const earthHit=ray.intersectObject(earth)[0];const hit=ray.intersectObject(cloud).find(h=>!earthHit||h.distance<earthHit.distance);if(hit?.index!==undefined){const r=latest.current.data[hit.index];if(r)latest.current.onSelect(r);}};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',click);
const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=2*Math.atan(Math.tan(19*Math.PI/180)/Math.min(1,w/h))*180/Math.PI;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();const selectionGroup=new THREE.Group();scene.add(selectionGroup);api.current={camera,controls,cloud,pointGeo,gridGroup,orbitGroup,geo,selectionGroup};let frame=0;function draw(){frame=requestAnimationFrame(draw);controls.autoRotate=latest.current.rotate;controls.update();renderer.render(scene,camera);}draw();return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();texture.dispose();scene.traverse((o:any)=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach((m:any)=>m.dispose())});renderer.dispose();renderer.domElement.remove();api.current=null;};},[]);
useEffect(()=>{const a=api.current;if(!a)return;const positions:number[]=[],colors:number[]=[];props.data.forEach(r=>{const p=a.geo(r.lat,r.lon,2+r.alt/6371*2);positions.push(p.x,p.y,p.z);const c=new THREE.Color(densityColor(r.density));colors.push(c.r,c.g,c.b);});a.pointGeo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));a.pointGeo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));a.pointGeo.computeBoundingSphere();a.cloud.visible=props.points;a.gridGroup.visible=props.grid;a.orbitGroup.visible=props.orbits;const visible=new Set(props.visibleOrbits);a.orbitGroup.children.forEach((l:any)=>l.visible=visible.has(l.userData.orbit));},[props.visibleOrbits,props.data,props.points,props.grid,props.orbits]);useEffect(()=>{const a=api.current;if(a)a.camera.position.setLength(Math.max(3,Math.min(14,7.8-props.zoom*.8)));},[props.zoom]);useEffect(()=>{const a=api.current;if(a&&props.focus){a.camera.position.copy(a.geo(props.focus.lat,props.focus.lon,a.camera.position.length()));a.controls.update();}},[props.focus]);useEffect(()=>{const a=api.current;if(!a)return;while(a.selectionGroup.children.length){const child=a.selectionGroup.children[0];child.geometry?.dispose();child.material?.dispose();a.selectionGroup.remove(child);}if(!props.region)return;const region=props.region;const start=a.geo(region.a.lat,region.a.lon,1);const ps:THREE.Vector3[]=[];if(region.type==='Coordinates'){const axis=Math.abs(start.y)>.95?new THREE.Vector3(1,0,0):new THREE.Vector3(0,1,0);const u=new THREE.Vector3().crossVectors(start,axis).normalize(),v=new THREE.Vector3().crossVectors(start,u).normalize();const ang=region.radius/6371;for(let i=0;i<=160;i++){const t=i/160*Math.PI*2;ps.push(start.clone().multiplyScalar(Math.cos(ang)).add(u.clone().multiplyScalar(Math.sin(ang)*Math.cos(t))).add(v.clone().multiplyScalar(Math.sin(ang)*Math.sin(t))).multiplyScalar(2.18));}}else{const end=a.geo(region.b.lat,region.b.lon,1),ang=start.angleTo(end);for(let i=0;i<=160;i++){const t=i/160;ps.push(start.clone().multiplyScalar(Math.sin((1-t)*ang)/Math.sin(ang)).add(end.clone().multiplyScalar(Math.sin(t*ang)/Math.sin(ang))).multiplyScalar(2.18));}}a.selectionGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(ps),new THREE.LineBasicMaterial({color:0xffe1a0,transparent:true,opacity:.95})));},[props.region]);return <div className="globe-canvas" ref={host} aria-label="Interactive 3D Earth. Drag to rotate, scroll to zoom, and click a measurement.">{error&&<div className="globe-error">{error}</div>}</div>}

